In [38]:
import pandas as pd
df = pd.read_csv('rect.csv')

In [39]:
df

     Unnamed: 0                                                  0
0             0  322.8525695800781,117.72525024414062,7.2192802...
1             1  316.5731201171875,118.24846649169922,6.1882324...
2             2  316.2164306640625,132.6868438720703,-13.174918...
3             3  317.718017578125,120.55618286132812,-17.941429...
4             4  314.1623229980469,132.9160919189453,-3.2316868...
..          ...                                                ...
96           96  315.13323974609375,127.19055938720703,-9.81531...
97           97  323.05535888671875,115.9223861694336,-0.814285...
98           98  317.007568359375,117.48397064208984,-3.8705859...
99           99  318.6416320800781,110.84397888183594,-14.12328...
100         100  319.9682922363281,133.80133056640625,-11.73374...

[101 rows x 2 columns]

In [40]:
df['Unnamed: 0']

0        0
1        1
2        2
3        3
4        4
      ...
96      96
97      97
98      98
99      99
100    100
Name: Unnamed: 0, Length: 101, dtype: int64

In [41]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [42]:
df

                                                     0
0    322.8525695800781,117.72525024414062,7.2192802...
1    316.5731201171875,118.24846649169922,6.1882324...
2    316.2164306640625,132.6868438720703,-13.174918...
3    317.718017578125,120.55618286132812,-17.941429...
4    314.1623229980469,132.9160919189453,-3.2316868...
..                                                 ...
96   315.13323974609375,127.19055938720703,-9.81531...
97   323.05535888671875,115.9223861694336,-0.814285...
98   317.007568359375,117.48397064208984,-3.8705859...
99   318.6416320800781,110.84397888183594,-14.12328...
100  319.9682922363281,133.80133056640625,-11.73374...

[101 rows x 1 columns]

In [43]:
df1 = df.T

In [44]:
df1

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,"322.8525695800781,117.72525024414062,7.2192802...","316.5731201171875,118.24846649169922,6.1882324...","316.2164306640625,132.6868438720703,-13.174918...","317.718017578125,120.55618286132812,-17.941429...","314.1623229980469,132.9160919189453,-3.2316868...","319.01788330078125,121.31864166259766,-15.8930...","316.4932861328125,130.2086181640625,0.34309107...","316.5068359375,122.12216186523438,-27.62328338...","320.489501953125,128.4571533203125,-2.77523756...","318.9017639160156,121.1119613647461,-15.995443...",...,"316.885009765625,121.22169494628906,-8.1569910...","319.8068542480469,124.45759582519531,-13.34025...","317.7102355957031,129.7052764892578,-11.504545...","320.0162353515625,113.78578186035156,2.5235285...","312.0926513671875,126.75857543945312,-6.658223...","315.13323974609375,127.19055938720703,-9.81531...","323.05535888671875,115.9223861694336,-0.814285...","317.007568359375,117.48397064208984,-3.8705859...","318.6416320800781,110.84397888183594,-14.12328...","319.9682922363281,133.80133056640625,-11.73374..."

In [45]:
# 첫번째 사진의 output에 대해 dataframe을 생성
tmp = df1[0].str.split(",")
df2 = pd.DataFrame(data=[tmp.str.get(j) for j in range(390)], index=range(390))
df2.loc[390] = "Rect"
df2 = df2.T
df2

,0,1,2,3,4,5,6,7,8,9,...,381,382,383,384,385,386,387,388,389,390
0,322.8525695800781,117.72525024414062,7.219280242919922,146.69349670410156,183.47140502929688,37.31773376464844,263.42449951171875,403.259033203125,-10.94093132019043,139.49391174316406,...,412.55426025390625,328.643798828125,-0.12880216538906097,478.0472717285156,269.8324890136719,48.6660270690918,471.85113525390625,275.5452880859375,70.40972137451172,Rect

In [46]:
# 2번째 사진부터 마지막 사진까지 각각 output을 구하고 그에 대한 dataframe을 생성하면서
# 동시에 df2(첫번째 사진의 dataframe)에 이어 붙인다.
for i in range(1, len(df1.columns)):
    temp = df1[i].str.split(",")
    df3 = pd.DataFrame(data=[temp.str.get(j) for j in range(390)], index=range(390))
    df3.loc[390] = "Rect"
    df3 = df3.T
    df2 = pd.concat([df2,df3])

In [47]:
df2 = df2.reset_index(drop=True)

In [48]:
df2

,0,1,2,3,4,5,6,7,8,9,...,381,382,383,384,385,386,387,388,389,390
0,322.8525695800781,117.72525024414062,7.219280242919922,146.69349670410156,183.47140502929688,37.31773376464844,263.42449951171875,403.259033203125,-10.94093132019043,139.49391174316406,...,412.55426025390625,328.643798828125,-0.12880216538906097,478.0472717285156,269.8324890136719,48.6660270690918,471.85113525390625,275.5452880859375,70.40972137451172,Rect
1,316.5731201171875,118.24846649169922,6.188232421875,158.91795349121094,184.83209228515625,46.36268615722656,256.37249755859375,392.20587158203125,-8.95351505279541,151.2936553955078,...,414.0511779785156,316.2858581542969,-4.071143627166748,493.0530090332031,259.79180908203125,40.33840560913086,494.59423828125,266.6371154785156,62.201934814453125,Rect
2,316.2164306640625,132.6868438720703,-13.174918174743652,158.81600952148438,188.66305541992188,32.52269744873047,258.72088623046875,398.47900390625,4.2813591957092285,151.9928741455078,...,421.0541687011719,322.8056945800781,1.6889359951019287,493.92828369140625,260.8556823730469,36.46966552734375,495.1876220703125,262.3345642089844,57.8802490234375,Rect
3,317.718017578125,120.55618286132812,-17.941429138183594,157.70765686035156,176.2725830078125,29.3885555267334,264.396728515625,403.7117004394531,9.000044822692871,153.4137725830078,...,412.89300537109375,330.83642578125,2.201235294342041,493.51043701171875,253.2552947998047,35.82716369628906,493.8096923828125,250.45774841308594,57.72550582885742,Rect
4,314.1623229980469,132.9160919189453,-3.23168683052063,158.05455017089844,194.24485778808594,41.09657669067383,262.3285827636719,397.13226318359375,-1.1152042150497437,153.11444091796875,...,412.1473693847656,324.5804748535156,-2.5936155319213867,498.7860107421875,262.11639404296875,36.98180389404297,502.6859130859375,265.7562561035156,58.91824722290039,Rect
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,315.13323974609375,127.19055938720703,-9.815315246582031,147.70831298828125,186.51597595214844,33.62666702270508,264.63079833984375,390.7188415527344,2.852548360824585,144.49746704101562,...,410.19134521484375,323.2985534667969,0.21497878432273865,494.410888671875,254.0025177001953,38.72566223144531,494.3033752441406,253.76673889160156,60.68436050415039,Rect
97,323.05535888671875,115.9223861694336,-0.8142858147621155,144.2453155517578,181.30357360839844,28.875652313232422,265.0675354003906,411.5266418457031,-7.212691783905029,137.0504608154297,...,415.6733703613281,330.1053771972656,4.194395542144775,467.3774108886719,265.1546325683594,50.589324951171875,457.79486083984375,268.9270324707031,72.44867706298828,Rect
98,317.007568359375,117.48397064208984,-3.8705859184265137,173.333740234375,182.2408905029297,41.9373664855957,262.4703063964844,407.69775390625,-0.8665118217468262,167.19403076171875,...,408.56048583984375,331.2025451660156,-2.660691022872925,487.2980651855469,264.4802551269531,36.06245422363281,490.2587890625,267.7789611816406,57.94125747680664,Rect
99,318.6416320800781,110.84397888183594,-14.123287200927734,154.47662353515625,175.130615234375,30.056432723999023,258.3719482421875,410.3614807128906,5.538763046264648,148.7736053466797,...,427.6643371582031,319.3584899902344,3.0469889640808105,497.23663330078125,257.8608703613281,36.127132415771484,497.7322998046875,259.2111511230469,56.7081184387207,Rect
100,319.9682922363281,133.80133056640625,-11.733747482299805,149.0632781982422,187.55029296875,28.092851638793945,255.90240478515625,402.9739074707031,3.1522934436798096,141.42420959472656,...,419.76776123046875,322.4519958496094,4.623888969421387,481.25115966796875,261.4380798339844,43.11731719970703,476.7766418457031,263.0310363769531,64.99681091308594,Rect

In [49]:
# 최종 csv파일을 얼굴형에 맞는 이름으로 저장한다.
# 계란형 - Egg, 둥근형 - Circle, 각진형 - Angled, ...
df2.to_csv('RectM.csv',index=False)